spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:router_watchdog}
    username: ${DB_USER:watchdog}
    password: ${DB_PASSWORD:watchdog}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

server:
  port: ${PORT:8080}
