server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/router_watchdog}
    username: ${SPRING_DATASOURCE_USERNAME:router_watchdog}
    password: ${SPRING_DATASOURCE_PASSWORD:router_watchdog}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true